[package]
name = "server"
version = "0.1.0"
authors = ["Qian Linfeng <thewawar@gmail.com>"]

[dependencies]
actix = "^0.6.1"
actix-web = "^0.6.14"
serde_json = "^1.0.22"
serde = "^1.0.67"
serde_derive = "^1.0.67"
redis = "^0.8.0"
